### PR TITLE
Plugin: Misc updates

### PR DESCRIPTION
**Pull request by renatonascalves**
Trac ticket: 

---
**This Pull Request is for code review only. Please keep all other discussion in the BuddyPress Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the WordPress Core Handbook for more details.**

### CODE REVIEW

**Comment by imath** [comment]
@renatonascalves I'm also playing into this area updating Node to the one WordPress uses (20.10.0). See https://github.com/buddypress/buddypress/pull/205

I don't think it conflicts, it's just FYI

**Comment by renatonascalves** [comment]
@imath I noticed it. Do you want to bundle this into #205 ?

**Comment by imath** [comment]
@renatonascalves It's up to you, you can SVN commit it and I'll rebase my PR once done, or I'm fine with bundling it 👍

**Comment by imath** [comment]
@renatonascalves I changed my mind, as I'm ready to commit #205 I'll bundle this PR in it. Thanks a lot for your contributions about it.

**Comment by renatonascalves** [comment]
@imath No problem at all. Thanks! 🙌🏾

**Pull request closed without merging**
