### PR TITLE
Need to update version of wordpress env package

### PR DESCRIPTION
**Pull request by narenin**
Trac ticket: https://buddypress.trac.wordpress.org/ticket/9236

The version is already removed in `env package` in `latest version` so updating the same version in `package.json`

https://github.com/WordPress/gutenberg/pull/63099

---
**This Pull Request is for code review only. Please keep all other discussion in the BuddyPress Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the WordPress Core Handbook for more details.**

### CODE REVIEW

**Comment by narenin** [comment]
@boonebgorges @imath could you please review this.

**Comment by imath** [comment]
Hi @narenin I just launched the Unit tests, if they give good results I'll commit your PR.

**Comment by narenin** [comment]
@imath Thanks for review this PR, as I can check now the unit test give good results.

**Review by renatonascalves — APPROVED** [review]
Good catch! ❤️

**Comment by renatonascalves** [comment]
@imath Just a reminder that we don't use `wp-env` in the github actions anymore.

**Pull request closed without merging**
