### PR TITLE
Implemented the PHPCS Fixes in `src/bp-templates/bp-nouveau/buddypress-functions.php`

### PR DESCRIPTION
**Pull request by narenin**
Trac ticket: https://buddypress.trac.wordpress.org/ticket/9230

---
**This Pull Request is for code review only. Please keep all other discussion in the BuddyPress Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the WordPress Core Handbook for more details.**

### CODE REVIEW

**Comment by narenin** [comment]
@ renatonascalves Could you please review this.

**Comment by narenin** [comment]
@renatonascalves @imath Could you please review this.

**Review by imath — COMMENTED** [review]
It's looking good. Thanks for your contribution @narenin I'll SVN commit it soon 👌

**Comment by narenin** [comment]
@imath Thanks for reviewing this and your prompt response.

**Pull request closed without merging**
